### ISSUE TITLE
Top right corner - link to GitHub should probably be changed

### ISSUE THREAD

**Issue by gregorywong** [FreeCodeCampHongKong/FreeCodeCampHongKong.github.io#10]
That repo is not the repo for this webpage.
We should probably link to one of the following instead:

1. https://github.com/FreeCodeCampHongKong/ (Main GitHub page for the org)

1. https://github.com/FreeCodeCampHongKong/FreeCodeCampHongKong.github.io (Actual repo for this page)

**Comment by andrealaw** [comment]
I think we should link it to the main Github page (the first link) as it's the place for others to look for information about FCCHK.
