### ISSUE TITLE
Preview sites for Pull Requests

### ISSUE THREAD

**Issue by isaackwan** [FreeCodeCampHongKong/FreeCodeCampHongKong.github.io#21]
Currently PRs are not preview-able. If a user wants to preview the effects of a PR he'd need to first clone it locally and run it. Things will get more complicated when Jekyll lands.

Proposal: Use netlify, free GitHub pages competitor, to automatically set up preview sites for each PR. [Preview here](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/)

Next steps: let me know if this sounds OK to you and I'll get this set up.

**Comment by gregorywong** [comment]
@isaackwan Thanks for sharing this resource! Your points are very valid and I think it would be great to have this in our arsenal. Much appreciated if you could help us set it up then :)

**Comment by isaackwan** [comment]
Neat, GitHub should have sent you an email @gregorywong for allowing Netlify to access the projects.

**Comment by gregorywong** [comment]
@isaackwan Just granted access. Thanks!

**Comment by isaackwan** [comment]
See #23 for an example of how this works in action -- click on the check mark to visit the preview site. Closing because the change is now implemented.

![screenshot from 2017-09-16 14-18-11](https://user-images.githubusercontent.com/1005813/30509734-fc4d64a2-9ae9-11e7-8fe4-6a5add226429.png)
