### ISSUE TITLE
Add FCC logo

### ISSUE THREAD

**Issue by andrealaw** [FreeCodeCampHongKong/FreeCodeCampHongKong.github.io#3]

**Comment by wcccl** [comment]
@BlacklBeard Please change the nav bar border to 0px

**Comment by gregorywong** [comment]
The logo should probably have "Hong Kong" in it as well. According to FCC, the font used is "saxmono".

Two options:
1) add the text after the logo
2) create new logo and use that one instead

**Comment by SWbottier** [comment]
Hi I've sketched up something wondering if we could be a little authentic but tweaking the logo a bit? 

<img width="923" alt="fcchk-sam" src="https://user-images.githubusercontent.com/17350261/30522713-1247c590-9c07-11e7-9d89-6d158ccfb2a4.png">

**Comment by gregorywong** [comment]
@SWbottier Wow! I love it! We should definitely use it.
