### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by andrealaw** [FreeCodeCampHongKong/FreeCodeCampHongKong.github.io#4]

**Comment by SWbottier** [comment]
May I ask what favicon is needed? Maybe I can work on this.

**Comment by gregorywong** [comment]
@SWbottier Do you think you'd be able to make a favicon using the FCCHK logo you designed? So instead of the FCC regular fire favicon we'd have the bauhinia one instead.

<img width="262" alt="screen shot 2017-09-20 at 6 39 06 pm" src="https://user-images.githubusercontent.com/1437804/30639833-1f60f35e-9e33-11e7-8a4b-70047486d6bb.png">

**Comment by andrealaw** [comment]
Thanks @SWbottier and @gregorywong !

The simplest solution is to create a 16x16px PNG image as shown above.
Put it under the root directory and add this line inside the **head** tags in **index.html**:

`<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">`

For your reference, in modern web development, we have favicons and app icons in different size and even with multiple designs. They are used not just for desktop users but also tablet and mobile users. You may start with the traditional favicon first and add more icons afterward. 
 
Quick reference: https://sympli.io/blog/2017/02/15/heres-everything-you-need-to-know-about-favicons-in-2017/

**Comment by andrealaw** [comment]
Another quick reference for better naming patterns: http://www.kylejlarson.com/blog/adding-an-icon-for-iphone-ipad-android-to-your-website/

Long read about favicon development and more information: https://css-tricks.com/favicon-quiz/

**Comment by SWbottier** [comment]
Which do you think should we use?

<img width="290" alt="screen shot 2017-09-21 at 11 32 24 am" src="https://user-images.githubusercontent.com/17350261/30677809-9cf526fe-9ec0-11e7-9ce8-b69926260d61.png">

I actually wonder if we can use a round favicon like Gh, basically just like the one we have in whatsapp. Comments

**Comment by andrealaw** [comment]
I prefer the right one as the design has less details and looks much clear in such a small size.

Round one can be achieved by saving a PNG file with a transparent background.

**Comment by gregorywong** [comment]
Same as Andrea.
