### ISSUE TITLE
Add details to README

### ISSUE THREAD

**Issue by gregorywong** [FreeCodeCampHongKong/FreeCodeCampHongKong.github.io#7]
Some things to add to the README file so that anyone can easily know what's going on:

- short "about" section, including link to see actual page: https://freecodecamphongkong.github.io/
- contributor guide (get content from Andrea's [notes to contributors](https://github.com/FreeCodeCampHongKong/FreeCodeCampHongKong.github.io/issues/6))
- A link to https://pages.github.com/ so people seeing this the first time can understand how we set this up using github pages.

**Comment by newbiegreen4ever** [comment]
Hi, would like to help with the issue //

**Comment by gregorywong** [comment]
@newbiegreen4ever 
I just sent you an invite to be a member of this org. Once you become a member, you can assign yourself to this task. Let me know if you need any help!
